# Generated by Django 5.1.3 on 2024-12-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dino_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='length',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
