# Generated by Django 5.1.3 on 2025-01-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dino_app', '0003_route_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='waypoints_list',
            field=models.JSONField(default='{}'),
        ),
    ]
