# Generated by Django 5.1.3 on 2025-01-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dino_app', '0004_route_waypoints_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='length',
        ),
        migrations.AddField(
            model_name='route',
            name='route_lenght',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='waypoints_list',
            field=models.JSONField(default='[]'),
        ),
    ]
