# Generated by Django 5.1.3 on 2025-01-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dino_app', '0005_remove_route_length_route_route_lenght_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='route_lenght',
            new_name='route_length',
        ),
    ]
