# Generated by Django 5.1.3 on 2025-01-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dino_app', '0006_rename_route_lenght_route_route_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='route_length',
            new_name='length',
        ),
    ]
