# Generated by Django 5.1.3 on 2025-01-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dino_app', '0007_rename_route_length_route_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='waypoints_list',
            field=models.CharField(),
        ),
    ]
