# Generated by Django 5.1.3 on 2025-01-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dino_app', '0008_alter_route_length_alter_route_waypoints_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='waypoints_list',
            field=models.JSONField(),
        ),
    ]
