# Generated by Django 5.1.3 on 2025-01-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dino_app', '0010_alter_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
