# Generated by Django 5.1.3 on 2025-01-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dino_app', '0013_alter_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
