# Generated by Django 5.1.3 on 2025-01-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dino_app', '0015_alter_route_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='icon',
            field=models.CharField(default=''),
        ),
    ]
