# Generated by Django 5.1.3 on 2025-01-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dino_app', '0016_route_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='trackpoints_list',
            field=models.JSONField(default="no data"),
            preserve_default=False,
        ),
    ]
